
// action types for reporting resources
export const REPORT_RESOURCE_URL_REQUEST = 'REPORT_RESOURCE_URL_REQUEST';
export const REPORT_RESOURCE_URL_SUCCESS = 'REPORT_RESOURCE_URL_SUCCESS';
export const REPORT_RESOURCE_URL_FAILURE = 'REPORT_RESOURCE_URL_FAILURE';

// action types for login and user creation
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';